import {colors, fonts} from '@constants';
import {Dimensions, StyleSheet} from 'react-native';

const width = Dimensions.get('window').width;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  bannerContainer: {
    height: 160,
    marginBottom: 15,
  },
  bannerCard: {
    width: width,
    height: 160,
    position: 'relative',
  },
  bannerImage: {
    borderRadius: 0,
    height: '100%',
    width: '100%',
  },
  bannerOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    padding: 15,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
  },
  bannerTitle: {
    fontSize: 18,
    fontFamily: fonts.MONTSERRAT_BOLD,
    color: colors.white,
    marginBottom: 3,
  },
  bannerSubtitle: {
    fontSize: 14,
    fontFamily: fonts.MONTSERRAT_MEDIUM,
    color: colors.lightGray,
  },
  paginationStyle: {
    bottom: 10,
  },
  paginationItem: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.primary,
  },
  quickActionsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingHorizontal: 15,
    paddingVertical: 12,
    backgroundColor: colors.white,
    marginBottom: 8,
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  quickActionItem: {
    alignItems: 'center',
    flex: 1,
  },
  quickActionIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.lightestGray,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  quickActionText: {
    fontSize: 11,
    fontFamily: fonts.MONTSERRAT_MEDIUM,
    color: colors.gray,
    textAlign: 'center',
  },
  tabBar: {
    backgroundColor: colors.white,
    borderBottomColor: colors.lighterGray,
    borderBottomWidth: 1,
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  tabContainer: {
    borderRadius: 15,
    marginHorizontal: 3,
    marginVertical: 6,
  },
  tabContainerActive: {
    borderRadius: 15,
    marginHorizontal: 3,
    marginVertical: 6,
    backgroundColor: colors.primary,
  },
  tabContainerInactive: {
    borderRadius: 15,
    marginHorizontal: 3,
    marginVertical: 6,
    backgroundColor: colors.white,
  },
  tabText: {
    paddingHorizontal: 15,
    paddingVertical: 8,
    fontSize: 13,
    fontFamily: fonts.MONTSERRAT_MEDIUM,
  },
  tabTextActive: {
    paddingHorizontal: 15,
    paddingVertical: 8,
    fontSize: 13,
    fontFamily: fonts.MONTSERRAT_MEDIUM,
    color: colors.white,
  },
  tabTextInactive: {
    paddingHorizontal: 15,
    paddingVertical: 8,
    fontSize: 13,
    fontFamily: fonts.MONTSERRAT_MEDIUM,
    color: colors.gray,
  },
  separator: {
    height: 1,
    width: '95%',
    alignSelf: 'center',
    backgroundColor: colors.lighterGray,
  },
  sectionHeader: {
    backgroundColor: colors.white,
    paddingTop: 15,
    paddingBottom: 8,
    paddingHorizontal: 15,
  },
  sectionHeaderText: {
    fontSize: 20,
    fontFamily: fonts.MONTSERRAT_BOLD,
    color: colors.black,
    marginBottom: 8,
  },
  sectionHeaderLine: {
    height: 2,
    width: 40,
    backgroundColor: colors.primary,
    borderRadius: 1,
  },
  itemContainer: {
    backgroundColor: colors.white,
    marginHorizontal: 12,
    marginVertical: 3,
    borderRadius: 12,
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  itemContent: {
    padding: 15,
  },
  itemInfo: {
    flex: 1,
  },
  itemTitle: {
    fontSize: 16,
    fontFamily: fonts.MONTSERRAT_BOLD,
    color: colors.black,
    marginBottom: 6,
  },
  itemDescription: {
    fontSize: 13,
    fontFamily: fonts.MONTSERRAT_MEDIUM,
    color: colors.gray,
    lineHeight: 18,
    marginBottom: 12,
  },
  itemFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  itemPrice: {
    fontSize: 18,
    fontFamily: fonts.MONTSERRAT_BOLD,
    color: colors.primary,
  },
  actionButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  favoriteButton: {
    width: 35,
    height: 35,
    borderRadius: 18,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.gray,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  addButton: {
    width: 35,
    height: 35,
    borderRadius: 18,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.primary,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 2,
  },
  quantityContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 18,
    paddingHorizontal: 8,
    paddingVertical: 4,
    minWidth: 80,
    justifyContent: 'space-between',
  },
  quantityButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.gray,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  quantityText: {
    fontSize: 14,
    fontFamily: fonts.MONTSERRAT_BOLD,
    color: colors.white,
    minWidth: 20,
    textAlign: 'center',
  },
  cartIconContainer: {
    position: 'relative',
  },
  cartBadge: {
    position: 'absolute',
    top: -8,
    right: -8,
    backgroundColor: colors.red,
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 4,
  },
  cartBadgeText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: 'bold',
  },
});
