import {colors, fonts} from '@constants';
import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: colors.lighterGray,
  },
  headerTitle: {
    fontSize: 20,
    fontFamily: fonts.MONTSERRAT_BOLD,
    color: colors.black,
  },
  favoritesCount: {
    fontSize: 15,
    fontFamily: fonts.MONTSERRAT_SEMIBOLD,
    color: colors.primary,
    backgroundColor: colors.white,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 15,
  },
  searchContainer: {
    paddingHorizontal: 20,
    paddingVertical: 20,
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: colors.lighterGray,
  },
  searchInput: {
    backgroundColor: colors.white,
    borderRadius: 30,
    paddingHorizontal: 25,
    paddingVertical: 15,
    fontSize: 16,
    fontFamily: fonts.MONTSERRAT_MEDIUM,
    color: colors.black,
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  contentContainer: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  favoriteItem: {
    backgroundColor: colors.white,
    borderRadius: 16,
    marginBottom: 20,
    marginHorizontal: 4,
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 6,
    borderWidth: 1,
    borderColor: colors.lighterGray,
  },
  itemContent: {
    flexDirection: 'row',
    padding: 18,
  },
  itemImage: {
    width: 90,
    height: 90,
    borderRadius: 12,
    marginRight: 18,
  },
  itemDetails: {
    flex: 1,
    justifyContent: 'space-between',
  },
  itemTitle: {
    fontSize: 18,
    fontFamily: fonts.MONTSERRAT_BOLD,
    color: colors.black,
    marginBottom: 6,
    lineHeight: 22,
  },
  itemDescription: {
    fontSize: 14,
    fontFamily: fonts.MONTSERRAT_MEDIUM,
    color: colors.gray,
    marginBottom: 10,
    lineHeight: 20,
  },
  itemFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  itemPrice: {
    fontSize: 20,
    fontFamily: fonts.MONTSERRAT_BOLD,
    color: colors.primary,
  },
  actionButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  addToCartButton: {
    padding: 10,
    borderRadius: 25,
    backgroundColor: colors.primary,
    shadowColor: colors.primary,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  removeButton: {
    padding: 10,
    borderRadius: 25,
    backgroundColor: colors.primary,
    shadowColor: colors.red,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
    paddingVertical: 60,
  },
  emptyIcon: {
    marginBottom: 30,
    opacity: 0.8,
  },
  emptyTitle: {
    fontSize: 26,
    fontFamily: fonts.MONTSERRAT_BOLD,
    color: colors.black,
    textAlign: 'center',
    marginBottom: 15,
  },
  emptySubtitle: {
    fontSize: 16,
    fontFamily: fonts.MONTSERRAT_MEDIUM,
    color: colors.gray,
    textAlign: 'center',
    lineHeight: 26,
    marginBottom: 40,
  },
  browseButton: {
    backgroundColor: colors.primary,
    paddingHorizontal: 35,
    paddingVertical: 18,
    borderRadius: 30,
    shadowColor: colors.primary,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  browseButtonText: {
    color: colors.white,
    fontSize: 17,
    fontFamily: fonts.MONTSERRAT_SEMIBOLD,
  },
  bulkActionsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: colors.lighterGray,
  },
  selectAllButton: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  selectAllText: {
    fontSize: 16,
    fontFamily: fonts.MONTSERRAT_MEDIUM,
    color: colors.primary,
    marginLeft: 8,
  },
  removeSelectedButton: {
    backgroundColor: colors.red,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
  },
  removeSelectedText: {
    color: colors.white,
    fontSize: 14,
    fontFamily: fonts.MONTSERRAT_SEMIBOLD,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    fontSize: 16,
    fontFamily: fonts.MONTSERRAT_MEDIUM,
    color: colors.gray,
    marginTop: 10,
  },
  categoryTag: {
    backgroundColor: colors.primary,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    marginTop: 8,
    alignSelf: 'flex-start',
  },
  categoryTagText: {
    color: colors.white,
    fontSize: 12,
    fontFamily: fonts.MONTSERRAT_SEMIBOLD,
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
  },
  ratingText: {
    fontSize: 12,
    fontFamily: fonts.MONTSERRAT_MEDIUM,
    color: colors.gray,
    marginLeft: 4,
  },
  swipeAction: {
    backgroundColor: colors.red,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    borderRadius: 16,
    marginBottom: 20,
    marginHorizontal: 4,
  },
  swipeActionText: {
    color: colors.white,
    fontSize: 14,
    fontFamily: fonts.MONTSERRAT_SEMIBOLD,
  },
  filterContainer: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: colors.lighterGray,
  },
  filterButton: {
    backgroundColor: colors.white,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    marginRight: 10,
  },
  filterButtonActive: {
    backgroundColor: colors.primary,
  },
  filterButtonText: {
    fontSize: 14,
    fontFamily: fonts.MONTSERRAT_MEDIUM,
    color: colors.gray,
  },
  filterButtonTextActive: {
    color: colors.white,
  },

  // FlatList styles
  flatList: {
    flex: 1,
  },

  flatListContent: {
    paddingBottom: 20,
  },
});
