export enum ScreenEnum {
  Login = 'Login',
  Signup = 'Signup',
  ForgotPassword = 'ForgotPassword',
  PasswordResetSuccess = 'PasswordResetSuccess',
  Home = 'Home',
  Chat = 'Chat',
  Calls = 'Calls',
  Status = 'Status',
  Profile = 'Profile',
  Settings = 'Settings',
  Contacts = 'Contacts',
  Product = 'Product',
  Map = 'Map',
  Welcome = 'Welcome',
  Inbox = 'Inbox',
}
