import {colors, fonts} from '@constants';
import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    backgroundColor: colors.background,
  },
  contentContainer: {
    paddingBottom: 60,
  },
  profileContainer: {
    alignItems: 'center',
    marginBottom: 30,
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  profileImage: {
    width: 120,
    height: 120,
    borderRadius: 60,
    marginBottom: 15,
    borderWidth: 3,
    borderColor: colors.primary,
  },
  username: {
    fontSize: 24,
    fontFamily: fonts.MONTSERRAT_BOLD,
    color: colors.black,
    marginBottom: 5,
  },
  userEmail: {
    fontSize: 16,
    fontFamily: fonts.MONTSERRAT_MEDIUM,
    color: colors.gray,
    marginBottom: 20,
  },
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
    marginBottom: 30,
    paddingHorizontal: 20,
  },
  statItem: {
    alignItems: 'center',
    flex: 1,
  },
  statNumber: {
    fontSize: 20,
    fontFamily: fonts.MONTSERRAT_BOLD,
    color: colors.primary,
    marginBottom: 5,
  },
  statLabel: {
    fontSize: 14,
    fontFamily: fonts.MONTSERRAT_MEDIUM,
    color: colors.gray,
  },
  optionsContainer: {
    width: '100%',
    paddingHorizontal: 20,
  },
  optionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 18,
    backgroundColor: colors.white,
    marginBottom: 8,
    borderRadius: 12,
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  optionIcon: {
    marginRight: 15,
    width: 24,
    alignItems: 'center',
  },
  optionText: {
    fontFamily: fonts.MONTSERRAT_SEMIBOLD,
    color: colors.black,
    fontSize: 16,
    flex: 1,
  },
  logoutText: {
    color: colors.red,
  },
  sectionTitle: {
    fontSize: 18,
    fontFamily: fonts.MONTSERRAT_BOLD,
    color: colors.black,
    marginBottom: 15,
    marginTop: 20,
    paddingHorizontal: 20,
  },
  editProfileButton: {
    backgroundColor: colors.primary,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
    marginTop: 10,
  },
  editProfileButtonText: {
    color: colors.white,
    fontFamily: fonts.MONTSERRAT_SEMIBOLD,
    fontSize: 14,
  },
  cartSummaryContainer: {
    marginBottom: 30,
  },
  cartSummaryCard: {
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 1,
    borderColor: colors.lighterGray,
  },
  cartSummaryInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  cartSummaryText: {
    marginLeft: 15,
    flex: 1,
  },
  cartSummaryTitle: {
    fontSize: 16,
    fontFamily: fonts.MONTSERRAT_BOLD,
    color: colors.black,
    marginBottom: 4,
  },
  cartSummarySubtitle: {
    fontSize: 14,
    fontFamily: fonts.MONTSERRAT_MEDIUM,
    color: colors.gray,
  },
  viewCartButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.lightestGray,
    justifyContent: 'center',
    alignItems: 'center',
  },
  favoritesSummaryContainer: {
    marginBottom: 30,
  },
  favoritesSummaryCard: {
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 1,
    borderColor: colors.lighterGray,
  },
  favoritesSummaryInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  favoritesSummaryText: {
    marginLeft: 15,
    flex: 1,
  },
  favoritesSummaryTitle: {
    fontSize: 16,
    fontFamily: fonts.MONTSERRAT_BOLD,
    color: colors.black,
    marginBottom: 4,
  },
  favoritesSummarySubtitle: {
    fontSize: 14,
    fontFamily: fonts.MONTSERRAT_MEDIUM,
    color: colors.gray,
  },
  viewFavoritesButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.lightestGray,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
